export const ACTION_TYPES = {
  GET_PRODUCTS: 'GET_PRODUCTS',
  ADD_TO_CART: 'ADD_TO_CART',
  REMOVE_ITEM: 'REMOVE_ITEM',
  FILTER_PRODUCTS: 'FILTER_PRODUCTS',
  LOCAL_STORAGE_TO_CART: 'LOCAL_STORAGE_TO_CART',
  DECREASE_QUANTITY: 'DECREASE_QUANTITY',
  INCREASE_QUANTITY: 'INCREASE_QUANTITY',
}